### ISSUE TITLE
Arm Control [EPIC]

### ISSUE THREAD

**Issue by vexandmore** [space-concordia-robotics/robotics-orin#9]
With new codebase for the CAN bus wheels, the arm control code needs to be rewritten. It is very messy right now, with a mix of code handling the logitech joystick, 3d mouse, and ps4 controller.
It should allow for the following control modes:

- [ ] Wheel control
- [ ] Arm control - forward kinematics (directly set each motor speed)
- [ ] Arm control - IK

Ideally it would support multiple controllers:

- [ ] Logitech joystick
- [ ] PS4 controller

This new code should be composed of the following parts:

- [ ] arm_control and wheel_control nodes which receive values for the arm and wheel motors and send them to the motors
- [ ] A joy_mapper node which listens to joystick messages and outputs semantic information to control the arm (described below)
- [ ] IK solver node

The joy_mapper node would work as follows:

- [ ] Detect which controller is connected (PS4 controller in either of two mappings, logitech joystick)
- [ ] Allow mode to be set (wheel, arm, arm ik)
- [ ] Have three topics, one per mode. Each will be a custom type, with semantic information. For wheel, it will be twist commands. For arm ik: axes for xz, pitch angle, axes for claw control. For arm forward kinematics, it will be axes for all six arm motors.
- [ ] Be configurable with a yaml file
